baseURL = "https://ruyceres.com/"
languageCode = "es"
title = "Letras Varias"
theme = "PaperMod"

[pagination]
  pagerSize = 10
enableRobotsTXT = true

[params]
  description = "Un cuaderno digital sobre lecturas, intuiciones y resonancias."
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  disableScrollToTop = false