baseURL = "https://ruyceres.com/"
languageCode = "es"
title = "Letras Varias"
theme = "PaperMod"

[pagination]
  pagerSize = 10
enableRobotsTXT = true

[params]
  description = "Blog de literatura"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  disableScrollToTop = false

[params.homeInfoParams]
  Title = "Letras Varias"
  Content = "Blog de literatura"